[package]
name = "simple-expand-tilde"
version = "0.1.5"
edition = "2021"

license = "MIT"
repository = "https://github.com/splurf/simple-expand-tilde"
authors = ["Evan Schwartzentruber <evandotschwartzentruber@gmail.com>"]
description = "An extremely tiny and reliable Rust library that parses tilde expansion."
keywords = ["expand", "tilde", "home", "directory", "path"]
categories = ["accessibility"]

[dependencies]
simple-home-dir = "0.3.3"

[profile.release]
lto = true
codegen-units = 1